query Shows($live: Boolean) {
  items {
    home {
      image {
        filename_disk
      }
    }
    shows(sort: "-date", filter: { live: { _eq: $live } }) {
      id
      title
      date
      slug
      live
      link
      artwork {
        id
      }
      audio {
        id
      }
      attachment {
        id
      }
      producers {
        producers_id {
          id
          first_name
          last_name
          slug
        }
      }
    }
  }
}
